export type InvoiceCharge = { amount: number; description: string; charge_date: string };
export type InvoicePayment = { amount: number; payment_date: string; method: string; reference?: string | null; status: string };

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, character => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character] || character));
const money = (value: number) => Number(value).toLocaleString("en-US", { style: "currency", currency: "USD" });
const displayDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });

export function buildInvoice(charges: InvoiceCharge[], payments: InvoicePayment[], generatedAt = new Date(), logoUrl = "https://production-command-six.vercel.app/detroit-decal-premium-transparent.png") {
  const invoiceNumber = `MS-${generatedAt.getFullYear()}${String(generatedAt.getMonth()+1).padStart(2,"0")}${String(generatedAt.getDate()).padStart(2,"0")}-${String(generatedAt.getTime()).slice(-4)}`;
  const chargesTotal = charges.reduce((sum, item) => sum + Number(item.amount), 0);
  const confirmed = payments.filter(item => item.status === "confirmed");
  const confirmedTotal = confirmed.reduce((sum, item) => sum + Number(item.amount), 0);
  const balance = Math.max(0, chargesTotal - confirmedTotal);
  const chargeRows = [...charges].sort((a,b)=>a.charge_date.localeCompare(b.charge_date)).map(item=>`<tr><td>${displayDate(item.charge_date)}</td><td>${escapeHtml(item.description)}</td><td class="amount">${money(Number(item.amount))}</td></tr>`).join("");
  const paymentRows = confirmed.length ? [...confirmed].sort((a,b)=>a.payment_date.localeCompare(b.payment_date)).map(item=>`<tr><td>${displayDate(item.payment_date)}</td><td>${escapeHtml(item.method)}${item.reference?` · ${escapeHtml(item.reference)}`:""}</td><td class="amount credit">−${money(Number(item.amount))}</td></tr>`).join("") : `<tr><td colspan="3" class="empty">No confirmed payments applied.</td></tr>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice ${invoiceNumber}</title><style>
  :root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#e9eeec;color:#17231f;font-family:Inter,Arial,sans-serif}.toolbar{position:sticky;top:0;display:flex;justify-content:flex-end;gap:10px;padding:12px 18px;background:#17382d}.toolbar button{border:0;border-radius:8px;padding:10px 16px;background:#fff;color:#17382d;font-weight:800;cursor:pointer}.sheet{width:min(900px,calc(100% - 28px));min-height:1080px;margin:28px auto;padding:54px 58px;background:#fff;box-shadow:0 18px 50px rgba(23,56,45,.18)}.header{display:flex;justify-content:space-between;gap:32px;padding-bottom:28px;border-bottom:4px solid #17382d}.logo{width:250px;height:105px;object-fit:contain;object-position:left center}.invoice-title{text-align:right}.invoice-title h1{margin:0;color:#17382d;font-size:2.6rem;letter-spacing:.08em}.invoice-title p{margin:8px 0 0;color:#64736d;font-size:.9rem}.meta{display:grid;grid-template-columns:1fr 1fr;gap:34px;padding:28px 0}.eyebrow{margin:0 0 8px;color:#75847e;font-size:.72rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.meta h2{margin:0 0 6px;font-size:1.05rem}.meta p{margin:3px 0;color:#45554f;line-height:1.45}.invoice-meta{text-align:right}.invoice-meta strong{display:inline-block;min-width:105px;color:#17231f}h3{margin:22px 0 8px;color:#17382d;font-size:.8rem;letter-spacing:.1em;text-transform:uppercase}table{width:100%;border-collapse:collapse}th{padding:11px 12px;background:#17382d;color:#fff;font-size:.75rem;letter-spacing:.06em;text-align:left;text-transform:uppercase}th:last-child,td.amount{text-align:right}td{padding:12px;border-bottom:1px solid #dfe7e3;font-size:.9rem;vertical-align:top}td:first-child{width:142px;color:#607069}.credit{color:#087052;font-weight:750}.empty{text-align:center;color:#72807b}.totals{width:min(390px,100%);margin:28px 0 0 auto;border-top:2px solid #17382d}.total-row{display:flex;justify-content:space-between;padding:9px 0;color:#52625c}.total-row strong{color:#17231f}.balance{margin-top:4px;padding:16px 18px;border-radius:10px;background:#17382d;color:#fff;font-size:1.15rem;font-weight:850}.balance strong{color:#fff}.terms{margin-top:52px;padding:18px 20px;border-left:4px solid #e5b13f;background:#f7f9f8;color:#4d5d57;font-size:.86rem;line-height:1.5}.footer{display:flex;justify-content:space-between;gap:24px;margin-top:42px;padding-top:18px;border-top:1px solid #dfe7e3;color:#687770;font-size:.75rem}.footer strong{display:block;color:#17382d;margin-bottom:4px}@media(max-width:650px){.sheet{margin:0;width:100%;padding:28px 22px;box-shadow:none}.header,.meta{grid-template-columns:1fr;display:grid}.invoice-title,.invoice-meta{text-align:left}.logo{width:210px;height:82px}}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:100%;min-height:0;margin:0;padding:.45in .5in;box-shadow:none}.header{padding-bottom:18px}.meta{padding:20px 0}.terms{margin-top:32px}.footer{margin-top:28px}@page{size:letter;margin:0}}
  </style></head><body><div class="toolbar"><button type="button" onclick="window.print()">Print / Save PDF</button></div><main class="sheet"><header class="header"><img class="logo" src="${escapeHtml(logoUrl)}" alt="Detroit Decal &amp; Apparel"><div class="invoice-title"><h1>INVOICE</h1><p>Production &amp; fulfillment services</p></div></header><section class="meta"><div><p class="eyebrow">Bill to</p><h2>Marsh Supply</h2><p>Whatupdoe Coir Mat Program</p></div><div class="invoice-meta"><p><strong>Invoice</strong> ${invoiceNumber}</p><p><strong>Issued</strong> ${generatedAt.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</p><p><strong>Terms</strong> Due upon receipt</p></div></section><h3>Charges</h3><table><thead><tr><th>Date</th><th>Description</th><th>Amount</th></tr></thead><tbody>${chargeRows}</tbody></table><h3>Payments applied</h3><table><thead><tr><th>Date</th><th>Payment details</th><th>Amount</th></tr></thead><tbody>${paymentRows}</tbody></table><section class="totals"><div class="total-row"><span>Total billed</span><strong>${money(chargesTotal)}</strong></div><div class="total-row"><span>Confirmed payments</span><strong>−${money(confirmedTotal)}</strong></div><div class="total-row balance"><span>Balance due</span><strong>${money(balance)}</strong></div></section><aside class="terms"><strong>Payment note</strong><br>Payment is due upon receipt. Please include invoice ${invoiceNumber} with your payment and record the payment in Production Command so the shared ledger stays current.</aside><footer class="footer"><div><strong>Detroit Decal &amp; Apparel, LLC</strong>Printing · Fulfillment · Distribution</div><div>Generated from the Production Command payment ledger</div></footer></main></body></html>`;
  return { html, invoiceNumber, balance };
}
