"use client";
import {useEffect,useRef,useState} from "react";
import type {PortalSession} from "@/lib/auth";
type Defect={id:string;quantity:number;received_date:string;reason:string;run_id:string|null;inventory_removed:boolean;credit_amount:number;credit_rate:number|null;credited_at:string|null;created_by_name:string;photos:string[]};
type Run={run_id:string;scheduled_date:string;stage:string};
export default function DefectiveMats({session,onChange}:{session:PortalSession;onChange:()=>Promise<void>}){
 const [records,setRecords]=useState<Defect[]>([]),[runs,setRuns]=useState<Run[]>([]),[deliveries,setDeliveries]=useState<{id:string;tracking_number:string}[]>([]);
 const [form,setForm]=useState({quantity:"",receivedDate:new Intl.DateTimeFormat("en-CA",{timeZone:"America/Detroit"}).format(new Date()),reason:"",runId:"",deliveryId:"",removeInventory:true});
 const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[rates,setRates]=useState<Record<string,string>>({});
 const recordId=useRef<string|null>(null);
 async function load(){const response=await fetch("/api/defective-mats",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setRecords(data.records);const [r,d]=await Promise.all([fetch("/api/run-breakdowns"),fetch("/api/operations")]);if(r.ok)setRuns((await r.json()).runs);if(d.ok)setDeliveries((await d.json()).deliveries.filter((v:{supply_type:string})=>v.supply_type==="mats"));}
 useEffect(()=>{load().catch(e=>setMessage(e.message));const timer=window.setInterval(()=>load().catch(()=>{}),30000);return()=>window.clearInterval(timer)},[]);
 async function upload(id:string,photo:File){
 if(photo.size>2500000||!["image/jpeg","image/png","image/webp"].includes(photo.type)){
  const url=URL.createObjectURL(photo);try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error("Could not read this photo. Use JPG, PNG, or WebP."));img.src=url});const canvas=document.createElement("canvas");const scale=Math.min(1,2000/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const context=canvas.getContext("2d");if(!context)throw new Error("Could not prepare photo.");context.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Could not prepare photo.")),"image/jpeg",.85));photo=new File([blob],"defective-mat.jpg",{type:"image/jpeg"});}finally{URL.revokeObjectURL(url)}
 }
 const body=new FormData();body.set("id",id);body.set("photo",photo);const response=await fetch("/api/defective-mats/photos",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error);}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage("");let saved=false;try{recordId.current ||= crypto.randomUUID();const response=await fetch("/api/defective-mats",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:recordId.current})});const data=await response.json();if(!response.ok)throw new Error(data.error);saved=true;for(const photo of files)await upload(recordId.current,photo);setMessage("Defective mats recorded. Issue credit below when ready.");}catch(e){setMessage((saved?"Record saved. Add any missing photos below. ":"")+(e instanceof Error?e.message:"Could not save."));}finally{if(saved){recordId.current=null;setFiles([]);setForm({...form,quantity:"",reason:""});await onChange().catch(()=>{});await load().catch(e=>setMessage(e.message));window.dispatchEvent(new Event("marsh-records-changed"));}setBusy(false);}}
 async function linkRun(record:Defect,runId:string){setBusy(true);try{const response=await fetch("/api/defective-mats",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"link_run",id:record.id,runId})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();window.dispatchEvent(new Event("marsh-records-changed"));setMessage("Production run linked.")}catch(e){setMessage(e instanceof Error?e.message:"Could not link run.")}finally{setBusy(false)}}
 async function credit(record:Defect){const rate=Number(rates[record.id]||14);if(!window.confirm(`Issue $${(rate*record.quantity).toFixed(2)} account credit for ${record.quantity} defective, unprinted mats?`))return;setBusy(true);try{const response=await fetch("/api/defective-mats",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:record.id,rate})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();await onChange();window.dispatchEvent(new Event("marsh-records-changed"));setMessage("Credit issued and applied to the shared ledger.");}catch(e){setMessage(e instanceof Error?e.message:"Could not issue credit.")}finally{setBusy(false)}}
 return <article className="panel operations-panel defect-panel" id="defective-mats"><h2>Defective mats &amp; prepayment credits</h2><p>Received mats that could not be printed.</p>
 {session.role==="admin"&&<form className="operations-form" onSubmit={save}><div className="form-row"><label>Defective quantity<input type="number" min="1" step="1" required value={form.quantity} onChange={e=>{recordId.current=null;setForm({...form,quantity:e.target.value})}}/></label><label>Received date<input type="date" required value={form.receivedDate} onChange={e=>setForm({...form,receivedDate:e.target.value})}/></label></div><div className="form-row"><label>Related delivery<select value={form.deliveryId} onChange={e=>setForm({...form,deliveryId:e.target.value})}><option value="">No delivery reference</option>{deliveries.map(d=><option key={d.id} value={d.id}>{d.tracking_number}</option>)}</select></label><label>Production run<select value={form.runId} onChange={e=>setForm({...form,runId:e.target.value})}><option value="">Not assigned to a run</option>{runs.map(r=><option key={r.run_id} value={r.run_id}>{r.scheduled_date} · {r.stage} · {r.run_id.slice(0,8)}</option>)}</select></label></div><label>Defect description / notes<textarea required maxLength={2000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label>Photos<input key={records.length} type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small>Large photos are resized automatically. You can add photos later.</small></label><label className="defect-checkbox"><input type="checkbox" checked={form.removeInventory} onChange={e=>setForm({...form,removeInventory:e.target.checked})}/>Remove from blank inventory</label><small>Uncheck if these defective mats were already removed or never counted in inventory.</small><button className="sync-button" disabled={busy}>{busy?"Saving…":"Record defective mats"}</button></form>}
 <div className="record-list">{!records.length&&<p>No defective mats recorded.</p>}{records.map(record=><div className="defect-record" key={record.id}><strong>{record.quantity} defective mats · {record.received_date}</strong><p>{record.reason}</p><small>{record.created_by_name} · {record.inventory_removed?"Removed from blank inventory":"Inventory unchanged"}{record.run_id?` · Run ${runs.find(r=>r.run_id===record.run_id)?.scheduled_date||record.run_id.slice(0,8)}`:""}</small>{session.role==="admin"&&<label>Related production run<select disabled={busy} value={record.run_id||""} onChange={e=>linkRun(record,e.target.value)}><option value="">Not assigned</option>{runs.map(r=><option key={r.run_id} value={r.run_id}>{r.scheduled_date} · {r.stage}</option>)}</select></label>}<div className="defect-photos">{record.photos.map(url=><a key={url} href={url} target="_blank" rel="noreferrer"><img src={url} alt="Defective mat evidence"/></a>)}</div>{session.role==="admin"&&<label>Add photo<input type="file" accept="image/*" disabled={busy} onChange={async e=>{const photo=e.target.files?.[0];if(!photo)return;setBusy(true);try{await upload(record.id,photo);await load();setMessage("Photo attached.")}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.")}finally{setBusy(false)}}}/></label>}
 {record.credited_at?<p className="record-state confirmed">Credit issued: ${Number(record.credit_amount).toFixed(2)} · {record.quantity} × ${Number(record.credit_rate).toFixed(2)}</p>:session.role==="admin"?<div className="defect-credit"><label>Credit per mat<input type="number" min="0.01" max="14" step="0.01" value={rates[record.id]??"14"} onChange={e=>setRates({...rates,[record.id]:e.target.value})}/></label><strong>Total ${(record.quantity*Number(rates[record.id]??14)).toFixed(2)}</strong><button className="sync-button" disabled={busy} onClick={()=>credit(record)}>Issue credit</button></div>:<p>Credit not yet issued</p>}</div>)}</div>{message&&<p role="status">{message}</p>}</article>;
}
