"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, CreditCard, ExternalLink, PackageSearch, Plus, RefreshCw, Trash2, Truck } from "lucide-react";
import type { PortalSession } from "@/lib/auth";

type Payment = { id:string; amount:number; payment_date:string; method:string; reference:string|null; submitted_by_name:string; submitted_by_role:string; status:"pending"|"confirmed"; created_at:string };
type Charge = { id:string; amount:number; description:string; charge_date:string; created_by_name:string; created_at:string };
type SupplyKey="mats"|"boxes"|"tape"|"thankYouCards"|"polyBags"|"ink";
type Delivery = { id:string; description:string; supplier:string|null; supply_type:SupplyKey; quantity:number; inventory_applied:boolean; carrier:string; tracking_number:string; tracking_url:string|null; status:"expected"|"in_transit"|"delivered"; submitted_by_name:string; created_at:string };

export default function FinancialLogistics({ session,onIncomingChange,onInventoryReceived,onBalanceChange }: { session: PortalSession; onIncomingChange:(values:Partial<Record<SupplyKey,number>>)=>void; onInventoryReceived:(key:SupplyKey,quantity:number)=>void; onBalanceChange:(balance:number)=>void }) {
  const [payments,setPayments]=useState<Payment[]>([]), [charges,setCharges]=useState<Charge[]>([]), [deliveries,setDeliveries]=useState<Delivery[]>([]), [message,setMessage]=useState(""), [updatingDelivery,setUpdatingDelivery]=useState<string|null>(null);
  const [payment,setPayment]=useState({amount:"",paymentDate:new Date().toISOString().slice(0,10),method:"ACH",reference:"",note:""});
  const [charge,setCharge]=useState({amount:"",chargeDate:new Date().toISOString().slice(0,10),description:""});
  const [delivery,setDelivery]=useState({supplyType:"mats" as SupplyKey,quantity:"",carrier:"Other",trackingNumber:""});
  const [prepaymentNotice,setPrepaymentNotice]=useState<{quantity:number;total:number}|null>(null);
  const matPrepaymentQuantity=delivery.supplyType==="mats" ? Number(delivery.quantity) : 0;
  const matPrepaymentTotal=Number.isFinite(matPrepaymentQuantity)&&matPrepaymentQuantity>0 ? matPrepaymentQuantity*14 : 0;
  const load=async()=>{const response=await fetch("/api/operations",{cache:"no-store"});if(response.ok){const data=await response.json();const loadedPayments=(data.payments||[]) as Payment[];const loadedCharges=(data.charges||[]) as Charge[];setPayments(loadedPayments);setCharges(loadedCharges);setDeliveries(data.deliveries||[]);const received=loadedPayments.filter(item=>item.status==="confirmed").reduce((sum,item)=>sum+Number(item.amount),0);const billed=loadedCharges.reduce((sum,item)=>sum+Number(item.amount),0);onBalanceChange(Math.max(0,billed-received));const totals:Partial<Record<SupplyKey,number>>={};for(const item of (data.deliveries||[]) as Delivery[]){if(!item.inventory_applied&&item.supply_type)totals[item.supply_type]=(totals[item.supply_type]||0)+Number(item.quantity)}onIncomingChange(totals)}};
  useEffect(()=>{load()},[]);
  const confirmedTotal=useMemo(()=>payments.filter(p=>p.status==="confirmed").reduce((sum,p)=>sum+Number(p.amount),0),[payments]);
  const pendingTotal=useMemo(()=>payments.filter(p=>p.status==="pending").reduce((sum,p)=>sum+Number(p.amount),0),[payments]);
  const chargesTotal=useMemo(()=>charges.reduce((sum,item)=>sum+Number(item.amount),0),[charges]);
  const balanceOwed=Math.max(0,chargesTotal-confirmedTotal);
  const send=async(body:object)=>{setMessage("");const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?"Saved successfully.":data.error);if(response.ok)await load();return response.ok};
  const confirm=async(id:string)=>{await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"confirm_payment",id})});await load()};
  const updateDelivery=async(id:string,status:Delivery["status"])=>{setMessage("");setUpdatingDelivery(id);setDeliveries(current=>current.map(item=>item.id===id?{...item,status}:item));try{const response=await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"delivery_status",id,status})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save delivery status.");if(data.inventoryAddition?.key)onInventoryReceived(data.inventoryAddition.key,Number(data.inventoryAddition.quantity));setMessage("Delivery status saved.");}catch(error){setMessage(error instanceof Error?error.message:"Could not save delivery status.");}finally{await load();setUpdatingDelivery(null)}};
  const refreshDelivery=async(id:string)=>{await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"refresh_delivery",id})});await load()};
  const deleteLedgerItem=async(type:"payment"|"charge",item:Payment|Charge)=>{const amount=Number(item.amount).toLocaleString(undefined,{style:"currency",currency:"USD"});const detail=type==="charge"?(item as Charge).description:`${(item as Payment).method} payment`;if(!window.confirm(`Delete the ${amount} ${detail}? This cannot be undone.`))return;setMessage("");const response=await fetch("/api/operations",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({type,id:item.id})});const data=await response.json();setMessage(response.ok?`${type==="charge"?"Charge":"Payment"} deleted.`:data.error||`Could not delete the ${type}.`);if(response.ok)await load()};
  const deleteDelivery=async(item:Delivery)=>{if(!window.confirm(`Delete this incoming shipment for ${Number(item.quantity).toLocaleString()} × ${item.description}?`))return;setMessage("");const response=await fetch("/api/operations",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})});const data=await response.json();setMessage(response.ok?"Incoming shipment deleted.":data.error||"Could not delete the incoming shipment.");if(response.ok)await load()};
  const orderedLabel=(item:Delivery)=>new Date(item.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
  return <section className="operations-section">
    <div className="dashboard-section-heading"><div><span className="section-icon"><CreditCard size={18}/></span><h2>Payments, Invoices &amp; Incoming Deliveries</h2></div><p>Shared financial and inbound shipment tracking</p></div>
    <div className="operations-grid">
      <article className="panel operations-panel"><div className="operations-title"><span className="metric-icon green"><CreditCard size={19}/></span><div><h2>Payment ledger</h2><p>Only confirmed payments count toward received funds.</p></div></div>
        <div className="ledger-totals billing-totals"><div className="balance-total"><span>Balance owed to Detroit Decal</span><strong>${balanceOwed.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div><span>Total billed</span><strong>${chargesTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div><span>Confirmed received</span><strong>${confirmedTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="pending-total"><span>Awaiting confirmation</span><strong>${pendingTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div></div>
        {session.canCreateCharges&&<form className="operations-form charge-form" onSubmit={async e=>{e.preventDefault();if(await send({type:"charge",...charge}))setCharge({...charge,amount:"",description:""})}}><div className="form-row"><label>Charge amount<input type="number" min="0.01" step="0.01" value={charge.amount} onChange={e=>setCharge({...charge,amount:e.target.value})} required/></label><label>Charge date<input type="date" value={charge.chargeDate} onChange={e=>setCharge({...charge,chargeDate:e.target.value})}/></label></div><label>Description<input value={charge.description} onChange={e=>setCharge({...charge,description:e.target.value})} placeholder="Production, fulfillment, packaging…" required/></label><button className="sync-button" type="submit"><Plus size={16}/>Add charge</button></form>}
        <form id="payment-entry" className={`operations-form${prepaymentNotice ? " payment-attention" : ""}`} onSubmit={async e=>{e.preventDefault();if(await send({type:"payment",...payment})){setPayment({...payment,amount:"",reference:"",note:""});setPrepaymentNotice(null)}}}><div className="form-row"><label>Amount<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} required/></label><label>Date<input type="date" value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})}/></label></div><div className="form-row"><label>Method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>ACH</option><option>Check</option><option>Card</option><option>Cash</option><option>Other</option></select></label><label>Reference<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})} placeholder="Check or transfer #"/></label></div><button className="sync-button" type="submit"><Plus size={16}/>{session.role==="admin"?"Add payment":"Submit payment sent"}</button><small>{session.role==="admin"?"Your entries post immediately.":"After sending payment, submit its details here for Detroit Decal to confirm."}</small></form>
        <div className="record-list charge-list">{charges.slice(0,4).map(item=><div className="record-row" key={item.id}><div><strong>${Number(item.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><span>{item.description} · {new Date(item.charge_date+"T12:00:00").toLocaleDateString()}</span></div><div className="record-actions"><span className="record-state pending">Billed</span>{session.role==="admin"&&<button className="ledger-delete" type="button" onClick={()=>deleteLedgerItem("charge",item)} title="Delete charge" aria-label={`Delete charge for ${item.description}`}><Trash2 size={15}/></button>}</div></div>)}</div>
        <div className="record-list">{payments.slice(0,6).map(p=><div className="record-row" key={p.id}><div><strong>${Number(p.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><span>{p.method} · {new Date(p.payment_date+"T12:00:00").toLocaleDateString()} · {p.submitted_by_name}</span></div><div className="record-actions">{p.status==="confirmed"?<span className="record-state confirmed"><Check size={13}/>Confirmed</span>:session.role==="admin"?<button className="confirm-button" onClick={()=>confirm(p.id)}><Check size={14}/>Confirm received</button>:<span className="record-state pending">Pending confirmation</span>}{session.role==="admin"&&<button className="ledger-delete" type="button" onClick={()=>deleteLedgerItem("payment",p)} title="Delete payment" aria-label={`Delete ${p.method} payment`}><Trash2 size={15}/></button>}</div></div>)}</div>
      </article>
      <article className="panel operations-panel"><div className="operations-title"><span className="metric-icon blue"><PackageSearch size={19}/></span><div><h2>Incoming deliveries</h2><p>Materials Marsh has ordered for your facility.</p></div></div>
        <form className="operations-form" onSubmit={async e=>{e.preventDefault();const quantity=Number(delivery.quantity);const isMatPrepayment=delivery.supplyType==="mats";if(await send({type:"delivery",...delivery})){setDelivery({...delivery,quantity:"",trackingNumber:""});if(isMatPrepayment){setPrepaymentNotice({quantity,total:quantity*14});setPayment({...payment,amount:(quantity*14).toFixed(2),reference:`Prepayment for ${quantity} mats`})}}}}><div className="form-row"><label>Supply type<select value={delivery.supplyType} onChange={e=>setDelivery({...delivery,supplyType:e.target.value as SupplyKey})}><option value="mats">Blank coir mats</option><option value="boxes">Shipping boxes</option><option value="tape">Packing tape rolls</option><option value="thankYouCards">Thank-you cards</option><option value="polyBags">Poly bags</option><option value="ink">Black ink (%)</option></select></label><label>Quantity<input type="number" min="0.01" step="0.01" value={delivery.quantity} onChange={e=>setDelivery({...delivery,quantity:e.target.value})} required/></label></div>{matPrepaymentTotal>0&&<div className="live-prepayment"><CreditCard size={19}/><div><strong>Prepayment due: ${matPrepaymentTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong><span>{matPrepaymentQuantity} mats × $14.00 · $12 decoration + $2 fulfillment per mat</span></div></div>}<label>UPS or FedEx tracking number<input value={delivery.trackingNumber} onChange={e=>setDelivery({...delivery,trackingNumber:e.target.value})} placeholder="Carrier is detected automatically" required/></label><button className="sync-button" type="submit"><Plus size={16}/>Track incoming delivery</button><small>Shown as incoming until an admin confirms receipt; then the tile count increases.</small></form>
        {prepaymentNotice&&<div className="saved-prepayment-reminder"><CreditCard size={22}/><div><strong>${prepaymentNotice.total.toLocaleString(undefined,{minimumFractionDigits:2})} mat prepayment is due</strong><span>{prepaymentNotice.quantity} mats were added. Send payment, then record it in the payment ledger.</span></div><button type="button" onClick={()=>document.getElementById("payment-entry")?.scrollIntoView({behavior:"smooth",block:"center"})}>Go to payment</button></div>}
        <div className="record-list delivery-list">{deliveries.slice(0,6).map(d=><div className="delivery-row" key={d.id}><span className="delivery-icon"><Truck size={17}/></span><div className="delivery-details"><strong>{Number(d.quantity).toLocaleString()} × {d.description}</strong><span>{d.carrier} · {d.tracking_url?<a href={d.tracking_url} target="_blank" rel="noreferrer">{d.tracking_number} <ExternalLink size={11}/></a>:d.tracking_number}</span><b>Date ordered: {orderedLabel(d)}</b></div><button className="tracking-refresh" type="button" onClick={()=>refreshDelivery(d.id)} title="Refresh carrier tracking" aria-label="Refresh carrier tracking"><RefreshCw size={14}/></button><select aria-label={`Status for ${d.description}`} value={d.status} disabled={updatingDelivery===d.id} onChange={e=>updateDelivery(d.id,e.target.value as Delivery["status"])}><option value="expected">Expected</option><option value="in_transit">In transit</option><option value="delivered" disabled={session.role!=="admin"}>Arrived</option></select>{session.role==="admin"&&<button className="delivery-delete" type="button" onClick={()=>deleteDelivery(d)} title="Delete incoming shipment" aria-label={`Delete incoming shipment for ${d.description}`}><Trash2 size={15}/></button>}</div>)}</div>
      </article>
    </div>{message&&<div className="operations-message">{message}</div>}
  </section>;
}
