"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, CreditCard, ExternalLink, PackageSearch, Plus, RefreshCw, Truck } from "lucide-react";
import type { PortalSession } from "@/lib/auth";

type Payment = { id:string; amount:number; payment_date:string; method:string; reference:string|null; submitted_by_name:string; submitted_by_role:string; status:"pending"|"confirmed"; created_at:string };
type SupplyKey="mats"|"boxes"|"tape"|"thankYouCards"|"polyBags"|"ink";
type Delivery = { id:string; description:string; supplier:string|null; supply_type:SupplyKey; quantity:number; inventory_applied:boolean; carrier:string; tracking_number:string; tracking_url:string|null; tracking_message:string|null; eta_start:string|null; eta_end:string|null; status:"expected"|"in_transit"|"delivered"; submitted_by_name:string };

export default function FinancialLogistics({ session,onIncomingChange,onInventoryReceived }: { session: PortalSession; onIncomingChange:(values:Partial<Record<SupplyKey,number>>)=>void; onInventoryReceived:(key:SupplyKey,quantity:number)=>void }) {
  const [payments,setPayments]=useState<Payment[]>([]), [deliveries,setDeliveries]=useState<Delivery[]>([]), [message,setMessage]=useState("");
  const [payment,setPayment]=useState({amount:"",paymentDate:new Date().toISOString().slice(0,10),method:"ACH",reference:"",note:""});
  const [delivery,setDelivery]=useState({supplyType:"mats" as SupplyKey,quantity:"",carrier:"Other",trackingNumber:""});
  const load=async()=>{const response=await fetch("/api/operations",{cache:"no-store"});if(response.ok){const data=await response.json();setPayments(data.payments||[]);setDeliveries(data.deliveries||[]);const totals:Partial<Record<SupplyKey,number>>={};for(const item of (data.deliveries||[]) as Delivery[]){if(!item.inventory_applied&&item.supply_type)totals[item.supply_type]=(totals[item.supply_type]||0)+Number(item.quantity)}onIncomingChange(totals)}};
  useEffect(()=>{load()},[]);
  const confirmedTotal=useMemo(()=>payments.filter(p=>p.status==="confirmed").reduce((sum,p)=>sum+Number(p.amount),0),[payments]);
  const pendingTotal=useMemo(()=>payments.filter(p=>p.status==="pending").reduce((sum,p)=>sum+Number(p.amount),0),[payments]);
  const send=async(body:object)=>{setMessage("");const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?"Saved successfully.":data.error);if(response.ok)await load();return response.ok};
  const confirm=async(id:string)=>{await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"confirm_payment",id})});await load()};
  const updateDelivery=async(id:string,status:Delivery["status"])=>{const response=await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"delivery_status",id,status})});const data=await response.json();if(response.ok&&data.inventoryAddition?.key)onInventoryReceived(data.inventoryAddition.key,Number(data.inventoryAddition.quantity));else if(!response.ok)setMessage(data.error);await load()};
  const refreshDelivery=async(id:string)=>{await fetch("/api/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"refresh_delivery",id})});await load()};
  const windowLabel=(item:Delivery)=>item.eta_start?`${new Date(item.eta_start+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}${item.eta_end&&item.eta_end!==item.eta_start?` – ${new Date(item.eta_end+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}`:""}`:"Window not entered";
  return <section className="operations-section">
    <div className="dashboard-section-heading"><div><span>03</span><h2>Payments &amp; Incoming Deliveries</h2></div><p>Shared financial and inbound shipment tracking</p></div>
    <div className="operations-grid">
      <article className="panel operations-panel"><div className="operations-title"><span className="metric-icon green"><CreditCard size={19}/></span><div><h2>Payment ledger</h2><p>Only confirmed payments count toward received funds.</p></div></div>
        <div className="ledger-totals"><div><span>Confirmed received</span><strong>${confirmedTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="pending-total"><span>Awaiting confirmation</span><strong>${pendingTotal.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div></div>
        <form className="operations-form" onSubmit={async e=>{e.preventDefault();if(await send({type:"payment",...payment}))setPayment({...payment,amount:"",reference:"",note:""})}}><div className="form-row"><label>Amount<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} required/></label><label>Date<input type="date" value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})}/></label></div><div className="form-row"><label>Method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>ACH</option><option>Check</option><option>Card</option><option>Cash</option><option>Other</option></select></label><label>Reference<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})} placeholder="Check or transfer #"/></label></div><button className="sync-button" type="submit"><Plus size={16}/>Add payment</button><small>{session.role==="admin"?"Your entries post immediately.":"Your entry will await Detroit Decal confirmation."}</small></form>
        <div className="record-list">{payments.slice(0,6).map(p=><div className="record-row" key={p.id}><div><strong>${Number(p.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><span>{p.method} · {new Date(p.payment_date+"T12:00:00").toLocaleDateString()} · {p.submitted_by_name}</span></div><div>{p.status==="confirmed"?<span className="record-state confirmed"><Check size={13}/>Confirmed</span>:session.role==="admin"?<button className="confirm-button" onClick={()=>confirm(p.id)}><Check size={14}/>Confirm received</button>:<span className="record-state pending">Pending confirmation</span>}</div></div>)}</div>
      </article>
      <article className="panel operations-panel"><div className="operations-title"><span className="metric-icon blue"><PackageSearch size={19}/></span><div><h2>Incoming deliveries</h2><p>Materials Marsh has ordered for your facility.</p></div></div>
        <form className="operations-form" onSubmit={async e=>{e.preventDefault();if(await send({type:"delivery",...delivery}))setDelivery({...delivery,quantity:"",trackingNumber:""})}}><div className="form-row"><label>Supply type<select value={delivery.supplyType} onChange={e=>setDelivery({...delivery,supplyType:e.target.value as SupplyKey})}><option value="mats">Blank coir mats</option><option value="boxes">Shipping boxes</option><option value="tape">Packing tape rolls</option><option value="thankYouCards">Thank-you cards</option><option value="polyBags">Poly bags</option><option value="ink">Black ink (%)</option></select></label><label>Quantity<input type="number" min="0.01" step="0.01" value={delivery.quantity} onChange={e=>setDelivery({...delivery,quantity:e.target.value})} required/></label></div><label>UPS or FedEx tracking number<input value={delivery.trackingNumber} onChange={e=>setDelivery({...delivery,trackingNumber:e.target.value})} placeholder="Carrier is detected automatically" required/></label><button className="sync-button" type="submit"><Plus size={16}/>Track incoming delivery</button><small>Shown as incoming until an admin confirms receipt; then the tile count increases.</small></form>
        <div className="record-list delivery-list">{deliveries.slice(0,6).map(d=><div className="delivery-row" key={d.id}><span className="delivery-icon"><Truck size={17}/></span><div><strong>{Number(d.quantity).toLocaleString()} × {d.description}</strong><span>{d.supplier?`${d.supplier} · `:""}{d.carrier} · {d.tracking_url?<a href={d.tracking_url} target="_blank" rel="noreferrer">{d.tracking_number} <ExternalLink size={11}/></a>:d.tracking_number}</span><b>{windowLabel(d)}</b>{d.tracking_message&&<em>{d.tracking_message}</em>}</div><button className="tracking-refresh" onClick={()=>refreshDelivery(d.id)} title="Refresh carrier tracking"><RefreshCw size={14}/></button><select value={d.status} onChange={e=>updateDelivery(d.id,e.target.value as Delivery["status"])}><option value="expected">Expected</option><option value="in_transit">In transit</option><option value="delivered" disabled={session.role!=="admin"}>Received</option></select></div>)}</div>
      </article>
    </div>{message&&<div className="operations-message">{message}</div>}
  </section>;
}
