"use client";
import {useEffect,useState} from "react";
const designs={whatupdoe:"Whatupdoe",did_you_call_first:"Did You Call First?",upside_down_welcome:"Upside Down Welcome",marsh_supply:"Marsh Supply"};
type Mix=Record<keyof typeof designs,number>;
type Run={run_id:string;scheduled_date:string;stage:string;forecast:Mix;actual:Mix|null;notes:string;updated_at:string};
type Defect={id:string;run_id:string|null;quantity:number;credit_amount:number;reason:string};
const total=(mix:Mix|null)=>mix?Object.values(mix).reduce((a,b)=>a+Number(b),0):null;
export default function RunBreakdowns({isAdmin}:{isAdmin:boolean}){
 const [runs,setRuns]=useState<Run[]>([]),[defects,setDefects]=useState<Defect[]>([]),[edit,setEdit]=useState<Run|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/run-breakdowns",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setRuns(d.runs);setDefects(d.defects);}
 useEffect(()=>{const refresh=()=>load().catch(e=>setMessage(e.message));refresh();window.addEventListener("marsh-records-changed",refresh);const timer=window.setInterval(refresh,10000);return()=>{window.removeEventListener("marsh-records-changed",refresh);window.clearInterval(timer)}},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!edit||busy)return;setBusy(true);try{const r=await fetch("/api/run-breakdowns",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({runId:edit.run_id,actual:edit.actual,notes:edit.notes,expectedUpdatedAt:edit.updated_at})});const d=await r.json();if(!r.ok)throw new Error(d.error);setEdit(null);await load();setMessage("Actual printed quantities saved.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}}
 return <details className="compact-run-breakdown post-run-breakdown"><summary>Post-run breakdowns &amp; quantity adjustments</summary><p>Keep the original forecast and record what was actually printed. Stock transfers remain in Printed mats.</p>{runs.map(run=>{const linked=defects.filter(d=>d.run_id===run.run_id),bad=linked.reduce((s,d)=>s+d.quantity,0),credit=linked.reduce((s,d)=>s+Number(d.credit_amount),0);return <section className="defect-record" key={run.run_id}><h3>{run.scheduled_date} · {run.stage}</h3><p>Forecast: <strong>{total(run.forecast)}</strong> · Defective: <strong>{bad}</strong> · Actual printed: <strong>{total(run.actual)??"Not recorded"}</strong> · Credit: <strong>${credit.toFixed(2)}</strong></p><div className="run-table-wrap"><table><thead><tr><th>Design</th><th>Forecast</th><th>Actual printed</th></tr></thead><tbody>{Object.entries(designs).map(([key,label])=><tr key={key}><td>{label}</td><td>{run.forecast[key as keyof Mix]}</td><td>{run.actual?.[key as keyof Mix]??"—"}</td></tr>)}</tbody></table></div>{linked.map(d=><p key={d.id}><a href="#defective-mats">{d.quantity} defective mats</a> · {d.reason}</p>)}{run.notes&&<p>{run.notes}</p>}{isAdmin&&<button className="plan-edit-button" onClick={()=>{setMessage("");setEdit({...run,actual:run.actual||{...run.forecast}})}}>Adjust printed quantities</button>}{edit?.run_id===run.run_id&&<form className="operations-form" onSubmit={save}>{Object.entries(designs).map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="1" required value={edit.actual?.[key as keyof Mix]??0} onChange={e=>setEdit({...edit,actual:{...edit.actual!,[key]:Number(e.target.value)}})}/></label>)}<label>Adjustment notes<textarea value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><p>Actual total: {total(edit.actual)} · Forecast minus defects: {Math.max(0,(total(run.forecast)||0)-bad)}</p><button className="sync-button" disabled={busy}>Save actual quantities</button><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></form>}</section>})}{message&&<p role="status">{message}</p>}</details>;
}
